input:
  redis_list:
    url: "redis://localhost:6379"
    key: "firewall_logs"
    timeout: "5s"

pipeline:
  threads: 1
  processors:
  - firewall_anomaly_detector:
      window_seconds: 60
      model_path: "/etc/plugin/model.pkl"
      score_threshold: 0.7
      redis_config:
        address: "localhost:6379"
        password: ""
        db: 0
        key: "firewall_logs"
      kafka_config:
        brokers: ["localhost:9092"]
        anomaly_topic: "firewall-anomalies"
        normal_topic: "firewall-normal"
      sources:
        fortinet.firewall:
          metric: "connection_count"
        paloalto.firewall:
          metric: "bytes_sent"
        checkpoint.firewall:
          metric: "bytes_recv"

output:
  stdout: {}

# Usage: ./firewall-anomaly-detector -c config/firewall_anomaly_detector_stdout.yaml 